### ISSUE TITLE
Error in log after image_processing.scan. Scan fails.

### ISSUE THREAD

**Issue by aptonline** [robmarkcole/HASS-Deepstack-scene#1]
Just setup scene in 0.110.0 and getting the following error:

```
Log Details (ERROR)
Logger: homeassistant.helpers.entity
Source: custom_components/deepstack_scene/image_processing.py:88 
First occurred: 11:36:06 (1 occurrences) 
Last logged: 11:36:06

Update for image_processing.deepstack_scene_front_of_house fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 132, in async_update
    await self.async_process_image(image.content)
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 112, in async_process_image
    return await self.hass.async_add_job(self.process_image, image)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_scene/image_processing.py", line 88, in process_image
    self._dsscene.detect(image)
  File "/usr/local/lib/python3.7/site-packages/deepstack/core.py", line 132, in detect
    raise DeepstackException(f"Error from Deepstack: {error}")
NameError: name 'error' is not defined
```

**Comment by aptonline** [comment]
It does however seem to be getting through to the Deepstack container:

`[GIN] 2020/05/21 - 10:39:15 | 200 |     238.714µs |    192.168.1.12 | POST     /v1/vision/scene `

**Comment by robmarkcole** [comment]
This actually is an issue, actually a limitation of, the deepstack-python dependency which is [only catching a couple of types of error currently](https://github.com/robmarkcole/deepstack-python/blob/master/deepstack/core.py). Can you use CURL to check what is returned by deepstack? My guess is maybe you didnt activate the endpoint

**Comment by aptonline** [comment]
I think I have found the issue I didn't pass `VISION-SCENE=True` in the docker container :( .  Out of interest can I pass multiple VISION arguments to the docker container so for example have `Scene` and `Object` set? I'm guessing this would obviously impact on performance.

**Comment by robmarkcole** [comment]
yes you can
